language: php

env:
  - COVERAGE_PHP_VERSION=7.1
  - PHPUNIT_FLAGS=""

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - if [[ $TRAVIS_PHP_VERSION != $COVERAGE_PHP_VERSION ]]; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - if [[ $TRAVIS_PHP_VERSION == $COVERAGE_PHP_VERSION ]]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi
  - phpunit $PHPUNIT_FLAGS
  
after_script:
 - if [[ $TRAVIS_PHP_VERSION == $COVERAGE_PHP_VERSION ]]; then php vendor/bin/coveralls -v; fi
  
